site_name: gamesense
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
  
markdown_extensions:
  - codehilite:
      guess_lang: False
      use_pygments: True
      pygments_style: monokai
      noclasses: True
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"

plugins:
  - exclude:
      glob:
       - "*/README.md"
