name: Deployment
on: [push]

jobs:
  Deploy:
    runs-on: self-hosted
    
    steps:

      - name: Compile and build snippets
        run: |
          cd ~/actions-runner/_work/docs_compiler
          node .

      - name: Push new snippets to repository
        continue-on-error: true
        run: |
          cd ~/actions-runner/_work/docs_compiler
          cd dist
          git commit -m "Update snippets"
          git push

      - name: Build and publish VSCode extension
        run: |
          cd ~/actions-runner/_work/docs_compiler
          cd dist/vscode
          vsce package
          vsce publish
